fix specs
Summary:
Fixing types for function arguments:

Before:

```
> eqwalize-app wa_raft --clause-coverage
  Parsing modules           ████████████████████ 25/25
  EqWAlizing                ████████████████████ 25/25                                                                                                                                                                                                            error: clause_not_covered
    ┌─ erl/wa_raft/src/wa_raft_log_ets.erl:214:1
    │
214 │ ╭ trim_impl(_Log, '$end_of_table') ->
215 │ │     ok;
    │ ╰──────^ Clause is not covered by spec

See https://fb.me/eqwalizer_errors#clause_not_covered

error: clause_not_covered
     ┌─ erl/wa_raft/src/wa_raft_server.erl:1995:1
     │
1995 │ ╭ apply_op(LogIndex, undefined, _EffectiveTerm, #raft_state{name = Name, log_view = View, current_term = CurrentTerm}) ->
1996 │ │     ?RAFT_COUNT('raft.server.missing.log.entry'),
1997 │ │     ?LOG_ERROR("Server[~0p, term ~0p] failed to apply ~0p because log entry is missing from log covering ~0p to ~0p.",
1998 │ │         [Name, CurrentTerm, LogIndex, wa_raft_log:first_index(View), wa_raft_log:last_index(View)], #{domain => [whatsapp, wa_raft]}),
1999 │ │     exit({invalid_op, LogIndex});
     │ ╰────────────────────────────────^ Clause is not covered by spec

See https://fb.me/eqwalizer_errors#clause_not_covered

eqWAlized 9 module(s) (16 cached) in 0s
2 ERRORS
```

After - all covered

Differential Revision: D59275906

fbshipit-source-id: a09913130f842adfa3497a0d4b10c3e59efae2fc